name: Run OS tests

on:
  push:


jobs:
  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'

    - name: Level synthesis test
      run: |
        echo -e "y\n" | python3 ./make_level.py testlevel1 "Test Level 1" testskill "Test Skill"
        echo -e "y\n" | python3 ./make_level.py testlevel2 "Test Level 2" testskill

    - name: Set up environment
      run: |
        pip3 install .
        pip3 install flake8
        pip3 install pytest
        git config --global user.name "Github Actions"
        git config --global user.email "action@github.com"

    - name: Run tests
      run: python3 -m pytest gitgud

    - name: flake8 checks
      run: python3 -m flake8 .

  linux-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'

    - name: Level synthesis test
      run: |
        echo -e "y\n" | python3 ./make_level.py testlevel1 "Test Level 1" testskill "Test Skill"
        echo -e "y\n" | python3 ./make_level.py testlevel2 "Test Level 2" testskill

    - name: Set up environment
      run: |
        pip3 install .
        pip3 install flake8
        pip3 install pytest
        git config --global user.name "Github Actions"
        git config --global user.email "action@github.com"

    - name: Run tests
      run: python3 -m pytest gitgud

    - name: flake8 checks
      run: python3 -m flake8 .

  win-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'

    - name: Level synthesis test
      run: |
        echo -e "y\n" | python ./make_level.py testlevel1 "Test Level 1" testskill "Test Skill"
        echo -e "y\n" | python ./make_level.py testlevel2 "Test Level 2" testskill

    - name: Set up environment
      run: |
        pip install .
        pip install flake8
        pip install pytest
        git config --global user.name "Github Actions"
        git config --global user.email "action@github.com"

    - name: Run tests
      run: python -m pytest gitgud

    - name: flake8 checks
      run: python -m flake8 .
